import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "45",
    inStock: true,
    rating: 3,
    image: "/asset/boy1.jpg",
    categoryName: "boy",
    tag: "new arrival",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "4000",
    discount: "50",
    inStock: true,
    rating: 4,
    image: "/asset/boy2.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "40",
    inStock: true,
    rating: 5,
    image: "/asset/boy3.jpeg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "4000",
    discount: "20",
    inStock: true,
    rating: 4,
    image: "/asset/boy4.jpeg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "40",
    inStock: false,
    rating: 5,
    image: "/asset/boy5.jpeg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "1200",
    discount: "50",
    inStock: true,
    rating: 4,
    image: "/asset/boy6.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "800",
    discount: "50",
    inStock: true,
    rating: 2,
    image: "/asset/boy7.webp",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "3000",
    discount: "50",
    inStock: true,
    rating: 4,
    image: "/asset/boy8.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "1700",
    discount: "50",
    inStock: false,
    rating: 3,
    image: "/asset/boy9.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "60",
    inStock: true,
    rating: 4,
    image: "/asset/boy10.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "50",
    inStock: false,
    rating: 2,
    image: "/asset/girl2.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "1100",
    discount: "50",
    inStock: false,
    rating: 1,
    image: "/asset/girl3.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "50",
    inStock: true,
    rating: 4,
    image: "/asset/girl4.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Boy's Synthetic Kurta Pyjama Set Boy's Synthetic Kurta Pyjama Set",
    price: "2000",
    discount: "50",
    inStock: true,
    rating: 5,
    image: "/asset/boy11.jpg",
    categoryName: "boy",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "1250",
    discount: "30",
    inStock: false,
    rating: 2,
    image: "/asset/girl1.jpg",
    categoryName: "girl",
    tag: "new arrival",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "1400",
    discount: "50",
    inStock: true,
    rating: 1,
    image: "/asset/girl5.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "900",
    discount: "50",
    inStock: true,
    rating: 4,
    image: "/asset/girl6.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "1200",
    discount: "25",
    inStock: false,
    rating: 5,
    image: "/asset/girl7.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "5000",
    discount: "25",
    inStock: true,
    rating: 4,
    image: "/asset/girl8.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "1000",
    discount: "30",
    inStock: true,
    rating: 5,
    image: "/asset/girl9.jpg",
    categoryName: "girl",
  },
  {
    _id: uuid(),
    title: "Party wear 100% cotton",
    description:
      "Girl's Synthetic Kurta Pyjama Set Girl's Synthetic Kurta Pyjama Set",
    price: "2000",
    discount: "50",
    inStock: false,
    rating: 4,
    image: "/asset/girl10.jpg",
    categoryName: "girl",
  },
];
